(()=>{
const PIN='yk-admin-pin-v1', KNOW='yk-admin-knowledge-v1', LAND='yar-keshavarz-v4-single', CHAT='yk-yar-chat-v4', CONTENT='yk-content-v2', ACCESS='yk-pro-access-v2';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function lands(){const s=read(LAND,{});return Array.isArray(s.lands)?s.lands:[]}
function tx(){const s=read(LAND,{});return Array.isArray(s.transactions)?s.transactions:[]}
function chats(){const x=read(CHAT,[]);return Array.isArray(x)?x:[]}
function knowledge(){return read(KNOW,[])}
function fmt(n){return Number(n||0).toLocaleString('fa-IR')}
function userStats(){if($('#userCount'))$('#userCount').textContent='محلی';if($('#activeUsers'))$('#activeUsers').textContent='همین دستگاه';if($('#userStatus'))$('#userStatus').textContent='نسخه آفلاین آمار مرکزی کاربران ندارد.'}

function content(){const d=read(CONTENT,{});return {news:Array.isArray(d.news)?d.news:[],ads:Array.isArray(d.ads)?d.ads:[],cropGuides:d.cropGuides&&typeof d.cropGuides==='object'?d.cropGuides:{}}}
function saveContent(d){write(CONTENT,d)}
function renderContent(){
 const d=content();
 const nl=$('#newsAdminList'); if(nl)nl.innerHTML=d.news.length?d.news.map((x,i)=>`<div class="item"><b>${esc(x.title)}</b><small>${esc(x.cat||'عمومی')} · ${esc(x.text)}</small><button class="danger" data-news-del="${i}">حذف</button></div>`).join(''):'<p class="note">خبری ثبت نشده.</p>';
 nl?.querySelectorAll('[data-news-del]').forEach(b=>b.onclick=()=>{const d=content();d.news.splice(+b.dataset.newsDel,1);saveContent(d);renderContent()});
 const al=$('#adsAdminList'); if(al)al.innerHTML=d.ads.length?d.ads.map((x,i)=>`<div class="item"><b>${esc(x.title)}</b><small>${esc(x.cat||'عمومی')} · ${esc(x.text)} · ${esc(x.contact||'')}</small><button class="danger" data-ad-del="${i}">حذف</button></div>`).join(''):'<p class="note">آگهی ثبت نشده.</p>';
 al?.querySelectorAll('[data-ad-del]').forEach(b=>b.onclick=()=>{const d=content();d.ads.splice(+b.dataset.adDel,1);saveContent(d);renderContent()});
 const gl=$('#cropGuideList'), gs=d.cropGuides; if(gl)gl.innerHTML=Object.keys(gs).length?Object.entries(gs).map(([name,g])=>`<div class="item"><b>🌱 ${esc(name)}</b><small>تصاویر: ${Array.isArray(g.images)?g.images.length:0} · بیماری‌ها: ${Array.isArray(g.diseases)?g.diseases.length:0}</small><button class="danger" data-cg-del="${esc(name)}">حذف</button></div>`).join(''):'<p class="note">راهنمای اختصاصی ثبت نشده.</p>';
 gl?.querySelectorAll('[data-cg-del]').forEach(b=>b.onclick=()=>{const d=content();delete d.cropGuides[b.dataset.cgDel];saveContent(d);renderContent()});
}
function renderAccess(){
 const box=$('#accessList'); if(!box)return;
 const s=read(LAND,{}),p=s.profile||{};
 if(!p.id){p.id='u_'+Date.now().toString(36);s.profile=p;write(LAND,s)}
 const a=read(ACCESS,{});
 const isLocked=a[p.id]===false || a['*']===false;
 box.innerHTML=`<div class="item"><b>${esc(p.name||'کشاورز')}</b><small>شناسه پروفایل: ${esc(p.id)} · ${esc(p.phone||p.email||'اطلاعات تماس ثبت نشده')}</small><button class="${isLocked?'primary':'danger'}" id="toggleMyPro">${isLocked?'🔓 باز کردن دسترسی':'🔒 بستن دسترسی'}</button></div><div class="item"><b>همه کاربران این دستگاه</b><small>دسترسی پایه باز است؛ در صورت نیاز می‌توانی همه را قفل کنی.</small><button class="primary" id="openAllPro">⭐ باز کردن برای همه</button><button class="danger" id="closeAllPro" style="margin-top:7px">🔒 بستن برای همه</button></div>`;
 $('#toggleMyPro').onclick=()=>{const a=read(ACCESS,{});if(a[p.id]===false || a['*']===false){delete a[p.id];delete a['*']}else{a[p.id]=false}write(ACCESS,a);renderAccess()};
 $('#openAllPro').onclick=()=>{const a=read(ACCESS,{});delete a['*'];delete a[p.id];write(ACCESS,a);renderAccess()};
 $('#closeAllPro').onclick=()=>{const a=read(ACCESS,{});a['*']=false;write(ACCESS,a);renderAccess()};
}
function refresh(){const ls=lands(),t=tx(),area=ls.reduce((a,x)=>a+Number(x.area||x.hectare||0),0),income=t.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount||0),0),cost=t.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount||0),0);$('#landCount').textContent=fmt(ls.length);$('#areaTotal').textContent=fmt(area);$('#questionCount').textContent=fmt(chats().length);$('#profit').textContent=fmt(income-cost);$('#status').textContent=`${fmt(ls.length)} زمین، ${fmt(chats().length)} پیام محلی و ${fmt(knowledge().length)} دانش مدیریتی ذخیره شده است. متن چت‌ها در پنل مدیریت نمایش داده نمی‌شود.`;renderLands();renderKnowledge();renderContent();renderAccess();userStats()}
function renderLands(){const el=$('#landsList'),ls=lands();el.innerHTML=ls.length?ls.map((l,i)=>`<div class="item"><b>${esc(l.name||`زمین ${i+1}`)}</b><small>مساحت: ${esc(l.area??l.hectare??'ثبت نشده')} | محصول: ${esc(l.crop||l.product||'ثبت نشده')}</small><small>خاک: ${esc(l.soil||'—')} | آبیاری: ${esc(l.irrigation||'—')}</small></div>`).join(''):'<p class="note">هنوز زمینی ثبت نشده است.</p>'}
function renderKnowledge(){const el=$('#knowledgeList'),ks=knowledge();el.innerHTML=ks.length?ks.map((k,i)=>`<div class="item"><b>${esc(k.title)}</b><small>کلیدواژه: ${esc((k.keywords||[]).join('، '))}</small><small>${esc(k.answer)}</small><button class="danger" data-del="${i}">حذف</button></div>`).join(''):'<p class="note">دانش مدیریتی افزوده نشده است.</p>';el.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const a=knowledge();a.splice(+b.dataset.del,1);write(KNOW,a);refresh()})}
function tabs(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==b.dataset.tab)})}
function setup(){$('#app').hidden=false;$('#login').remove();tabs();refresh();$('#refresh').onclick=refresh;$('#refreshUsers').onclick=userStats;$('#openApp').onclick=()=>location.href='./';
$('#newsForm').onsubmit=e=>{e.preventDefault();const d=content();d.news.unshift({icon:'📰',cat:$('#newsCat').value.trim()||'عمومی',title:$('#newsTitle').value.trim(),text:$('#newsText').value.trim(),image:$('#newsImage').value.trim(),date:'امروز'});saveContent(d);e.target.reset();renderContent();alert('خبر فعال شد.')};
$('#adForm').onsubmit=e=>{e.preventDefault();const d=content();d.ads.unshift({icon:'📢',cat:$('#adCat').value.trim()||'عمومی',title:$('#adTitle').value.trim(),text:$('#adText').value.trim(),price:$('#adPrice').value.trim()||'استعلام قیمت',contact:$('#adContact').value.trim(),image:$('#adImage').value.trim()});saveContent(d);e.target.reset();renderContent();alert('آگهی فعال شد.')};
$('#cropGuideForm').onsubmit=e=>{e.preventDefault();const name=$('#cgCrop').value.trim();if(!name)return;const diseases=$('#cgDiseases').value.split(/\n/).map(line=>line.trim()).filter(Boolean).map(line=>{const p=line.split('|').map(x=>x.trim());return {name:p[0]||'بیماری',symptoms:p[1]||'',control:p[2]||'',images:(p[3]||'').split(',').map(x=>x.trim()).filter(Boolean)}});const d=content();d.cropGuides[name]={method:$('#cgMethod').value.trim(),seedDepth:$('#cgDepth').value.trim(),seedSpacing:$('#cgSpacing').value.trim(),soil:$('#cgSoil').value.trim(),plowing:$('#cgPlowing').value.trim(),images:$('#cgImages').value.split(/\n/).map(x=>x.trim()).filter(Boolean),diseases};saveContent(d);e.target.reset();renderContent();alert('راهنمای محصول ذخیره شد.')};
$('#knowledgeForm').onsubmit=e=>{e.preventDefault();const a=knowledge();a.push({title:$('#ktitle').value,keywords:$('#kkeys').value.split(/[,،]/).map(x=>x.trim()).filter(Boolean),answer:$('#kanswer').value,tags:$('#ktags').value.split(/[,،]/).map(x=>x.trim()).filter(Boolean),createdAt:new Date().toISOString()});write(KNOW,a);e.target.reset();refresh();alert('دانش ذخیره شد و در موتور آفلاین قابل استفاده است.')};
$('#export').onclick=()=>{const data={version:3,createdAt:new Date().toISOString(),privacy:'chat-history-excluded',knowledge:knowledge(),lands:lands(),transactions:tx()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='yar-keshavarz-offline-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(Array.isArray(d.knowledge))write(KNOW,d.knowledge);if(Array.isArray(d.lands))write(LAND,{...read(LAND,{}),lands:d.lands});if(Array.isArray(d.transactions))write(LAND,{...read(LAND,{}),transactions:d.transactions});refresh();alert('پشتیبان وارد شد. متن گفتگوهای کشاورزیار وارد یا نمایش داده نمی‌شود.')}catch{alert('فایل پشتیبان معتبر نیست.')}};
$('#clearKnowledge').onclick=()=>{if(confirm('همه دانش‌های مدیریتی حذف شود؟')){localStorage.removeItem(KNOW);refresh()}};
$('#changePin').onclick=async()=>{const old=prompt('رمز فعلی را وارد کنید');if(!old)return;if(await hash(old)!==localStorage.getItem(PIN))return alert('رمز فعلی نادرست است.');const n=prompt('رمز جدید حداقل ۴ رقم/حرف');if(!n||n.length<4)return alert('رمز جدید باید حداقل ۴ کاراکتر باشد.');localStorage.setItem(PIN,await hash(n));alert('رمز تغییر کرد.')};
$('#logout').onclick=()=>{sessionStorage.removeItem('yk-admin-auth');location.reload()}}
async function recoverPin(){const ok=confirm('رمز مدیریت همین دستگاه پاک شود؟\nاطلاعات زمین و مالی حذف نمی‌شود.');if(!ok)return;localStorage.removeItem(PIN);sessionStorage.removeItem('yk-admin-auth');alert('رمز مدیریت پاک شد. صفحه را دوباره باز کن تا رمز جدید بسازی.');location.href='./admin.html?v=offline-reset'}
async function boot(){const stored=localStorage.getItem(PIN);if(!stored){$('#loginHint').textContent='برای اولین ورود یک رمز حداقل ۴ رقمی بسازید.';$('#pin2').hidden=false}else $('#pin2').hidden=true;$('#loginForm').onsubmit=async e=>{e.preventDefault();const p=$('#pin').value;if(!stored){if(p!==$('#pin2').value||p.length<4)return $('#loginError').textContent='دو رمز یکسان نیستند یا کوتاه است.';localStorage.setItem(PIN,await hash(p));sessionStorage.setItem('yk-admin-auth','1');setup()}else{if(await hash(p)!==stored)return $('#loginError').textContent='رمز نادرست است.';sessionStorage.setItem('yk-admin-auth','1');setup()}};if(sessionStorage.getItem('yk-admin-auth')==='1')setup()}
document.addEventListener('DOMContentLoaded',()=>{const out=$('#logout');if(out)out.onclick=()=>{sessionStorage.removeItem('yk-admin-auth');location.href='./'};const rec=$('#recoverPin');if(rec){rec.addEventListener('click',e=>{e.preventDefault();recoverPin()})}});boot();
})();
